//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlickrStream.Infrastructure.Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlickrStream.Infrastructure.Test.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///		&quot;title&quot;: &quot;Uploads from everyone&quot;,
        ///		&quot;link&quot;: &quot;https:\/\/www.flickr.com\/photos\/&quot;,
        ///		&quot;description&quot;: &quot;&quot;,
        ///		&quot;modified&quot;: &quot;2022-09-04T06:36:17Z&quot;,
        ///	.
        /// </summary>
        internal static string DummyInvalidJson {
            get {
                return ResourceManager.GetString("DummyInvalidJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///		&quot;title&quot;: &quot;Uploads from everyone&quot;,
        ///		&quot;link&quot;: &quot;https:\/\/www.flickr.com\/photos\/&quot;,
        ///		&quot;description&quot;: &quot;&quot;,
        ///		&quot;modified&quot;: &quot;2022-09-04T06:36:17Z&quot;,
        ///		&quot;generator&quot;: &quot;https:\/\/www.flickr.com&quot;,
        ///		&quot;items&quot;: [
        ///	   {
        ///			&quot;title&quot;: &quot;2022-09-04_08-35-48&quot;,
        ///			&quot;link&quot;: &quot;https:\/\/www.flickr.com\/photos\/145925839@N02\/52331796437\/&quot;,
        ///			&quot;media&quot;: {&quot;m&quot;:&quot;https:\/\/live.staticflickr.com\/65535\/52331796437_17c967610a_m.jpg&quot;},
        ///			&quot;date_taken&quot;: &quot;2022-09-03T12:33:53-08:00&quot;,
        ///			&quot;description&quot;: &quot; &lt;p&gt;&lt;a href=\&quot;https:\/\/ww [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DummyValidJson {
            get {
                return ResourceManager.GetString("DummyValidJson", resourceCulture);
            }
        }
    }
}
